console.log('test')
console.log('test2')
console.log('test6')
console.log('test7')
console.log('test7.1')
console.log('test8')
console.log('test9')
console.log('test10')
console.log('update release')
console.log('update release2')
console.log('update release.patch should ok')
console.log('update patch update json gagal')