on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set Git user identity
        run: |
          git config --global user.email "daudzubaidi"
          git config --global user.name "daud.java@gmail.com"


      - name: Update package.json version
        run: |
          npm version patch --no-git-tag-version --allow-same-version
          git add package.json
          git status  # Add this line to check the status of the working tree
          git diff   # Add this line to see the difference before committing
          git commit -m "chore: update package.json version"
          git push
