on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:  # This line should be indented to align with 'uses'
          release-type: simple
    
      - name: Checkout code  # Corrected indentation
        uses: actions/checkout@v3
        
      - name: Update package.json version
        run: |
          cd $GITHUB_WORKSPACE  # Change to the correct working directory
          NEW_VERSION=$(jq -r '.releases[0].name' release-please-manifest.json | cut -d'v' -f2)
          npm version "${NEW_VERSION}" --no-git-tag-version --allow-same-version
          git add package.json
          git commit -m "chore: update package.json version to ${NEW_VERSION}"
          git push